### ISSUE TITLE
cc:start returns Access denied and Timeout

### ISSUE THREAD

**Issue by kirakira9** [worldsibu/convector-cli#35]
I have just followed the steps at 
https://worldsibu.github.io/convector/modules/getting_started.html
and try to execute the command _npm run cc:start -- test 1_  while **test** is my chaincode name.

It gives the following result:

Installing Chaincode test version 1.0 at org1
Error: Error endorsing chaincode: rpc error: code = Unknown desc = access denied: channel [] creator org [org1MSP]
...
Installing Chaincode test version 1.0 at org2
Error: error getting endorser client for install: endorser client failed to connect to localhost:7151: failed to create new connection: context deadline exceeded

**Comment by walmon** [comment]
Hi @kirakira9 a few things to troubleshoot:

- make sure to retry after the first error happens to discard temporary issues as internet connection
- make sure the Blockchain started successfully after `hurl new`

The error generally happens when the cryptographic materials are wrong or one service was restarted - like initiating a Blockchain network, restarting the computer and retrying.

**Comment by walmon** [comment]
This issue is closed due to inactivity
