### ISSUE TITLE
Prune unused Docker volumes

### ISSUE THREAD

**Issue by cherfia** [worldsibu/convector-cli#42]
Running `npm run env:clean` Hurley removes the containers only, it does not remove the generated volumes that are no longer used because re-running `npm run env:restart` will generate new volumes.

**Comment by walmon** [comment]
Hi @cherfia you are right, we don't erase the volumes because important data may be in there. `hurl clean` only cleans the path for a new network. If you'd like to purge the volumes you can do `docker volume purge`.

If the previous answer does not respond to your question feel free to reopen the ticket.
